# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws" do
  name "ws"
  desc "Workspace everything"
  homepage "https://github.com/andrew-malikov/ws"
  version "2026.03.28-3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws"

  on_macos do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_amd64.tar.gz"
      sha256 "2bc6e87fa5e82457ba942f5fb44f31fe5e2bbec9e6ce16fdf9cc7a1826d3fab5"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_arm64.tar.gz"
      sha256 "b25d5ebe7c554110fc4f55a7a93387c8f6b330c9a30b62408330d9905134cce0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_amd64.tar.gz"
      sha256 "b233874541a3cc81ddb983ad6d49e7c367ea921086a7441c7d15f7b92cd580b6"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_arm64.tar.gz"
      sha256 "00213e7f7965836fcc9b7f03cfd6987a51b47893a1a7ebf12c7158eb180ff466"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws"]
    end
  end

  # No zap stanza required
end
