# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws" do
  name "ws"
  desc "Workspace everything"
  homepage "https://github.com/andrew-malikov/ws"
  version "2026.02.28-1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws"

  on_macos do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_amd64.tar.gz"
      sha256 "9e9c6efd271f571ce665a3a6eb6ce25a7b55257cbda85e77f854b626adf34e66"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_arm64.tar.gz"
      sha256 "6d44628cc5ad7e9fd8ef1489b529e32c2a4dc2edc9db1c43ffc3649abe114f94"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_amd64.tar.gz"
      sha256 "a8c08f928763da50586fef04a8fb777fee775554c7cdcf3485394c5bf10a0c17"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_arm64.tar.gz"
      sha256 "f42dc91608b4daf7afc58593caa0f3df890d8e66473e54a939997d8f548f7eb7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws"]
    end
  end

  # No zap stanza required
end
