# This file was generated by GoReleaser. DO NOT EDIT.
cask "ws" do
  name "ws"
  desc "Workspace everything"
  homepage "https://github.com/andrew-malikov/ws"
  version "2026.02.22-1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ws"

  on_macos do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_amd64.tar.gz"
      sha256 "5ffc98dfa19b76ecdeb95c73a5f19f4a753cc7dc952f6ce616378d66c1e7d2ef"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_darwin_arm64.tar.gz"
      sha256 "1df11e010a9384a56849322a75c32e234a5b56cf43cbf0a6b4a6da5002f130d8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_amd64.tar.gz"
      sha256 "91dc0b01c6f978015d66c76696dda1afc5f0df73bf4af9fd15e267993ea09a61"
    end
    on_arm do
      url "https://github.com/andrew-malikov/workspace/releases/download/#{version}/ws_#{version}_linux_arm64.tar.gz"
      sha256 "03c98bea9f24492da734930509de086fb795ec5a76267193043193891e9cd605"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ws"]
    end
  end

  # No zap stanza required
end
